server:
  port: 80

mybatis:
  mapper-locations: classpath:mappers/**/**.xml

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3307/mydb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: lgs0503
    password: 0609